### ISSUE TITLE
Users/groups aren't being cleaned up properly after tests run in OCIS

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/owncloud-test-middleware#120]
Seems like users aren't being cleared up properly after test run in OCIS backend
Run a full feature file :
```
MIDDLEWARE_HOST="http://lhost.docker.internal:3000" BACKEND_HOST="https://host.docker.internal:9200" SERVER_HOST="https://host.docker.internal:9200" yarn test:acceptance:ocis features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature 
 ```

After the tests are run check if there are the users/groups created by the tests in the backend

![ocisUserList](https://user-images.githubusercontent.com/41103328/182522541-bd98cb33-e36f-4e60-a903-e7dffb7af2ec.png)

![ocisGroupList](https://user-images.githubusercontent.com/41103328/182522548-7bf0587c-8444-40bd-b896-c76495b6fc66.png)

There still are users/groups created by the tests that aren't cleared up yet.
Note most of the tests in the above feature file fail, maybe the users/groups aren't being cleared in failing cases only?

**Comment by kiranparajuli589** [comment]
The problem here is, we do not clean users/groups in the After scenarios. Everytime we have to create a new user or  group, we search for it. If it was found, we delete it before creating. This approach was working fine but For the search feature this leads us to problem like:
- 1st scenario create a user `bcd`
- 2nd scenarios creates user `abcd`
  - user created by fist scenario is still in the DB, because in this scenario we do not create user with the same `username`
  - If we go and search for user `bcd` in the sharing autocomplete, now we get 2 users.

Solution:
Cleanup state in the after Scenario.

**Comment by SwikritiT** [comment]
> The problem here is, we do not clean users/groups in the After scenarios. Everytime we have to create a new user or group, we search for it. If it was found, we delete it before creating. This approach was working fine but For the search feature this leads us to problem like:
> 
> * 1st scenario create a user `bcd`
> * 2nd scenarios creates user `abcd`
>   
>   * user created by fist scenario is still in the DB, because in this scenario we do not create user with the same `username`
>   * If we go and search for user `bcd` in the sharing autocomplete, now we get 2 users.
> 
> Solution: Cleanup state in the after Scenario.

No turns out we do clean up users in after scenarios. If I'm not wrong this should clean up the users for both backends 
https://github.com/owncloud/owncloud-test-middleware/blob/fd812e6a174c46784552db3ec2889cee5b1ba5e2/src/stepDefinitions/provisioningContext.js#L411-L412

**Comment by amrita-shrestha** [comment]
> The problem here is, we do not clean users/groups in the After scenarios. Everytime we have to create a new user or group, we search for it. If it was found, we delete it before creating. This approach was working fine but For the search feature this leads us to problem like:
> 
> * 1st scenario create a user `bcd`
> * 2nd scenarios creates user `abcd`
>   
>   * user created by fist scenario is still in the DB, because in this scenario we do not create user with the same `username`
>   * If we go and search for user `bcd` in the sharing autocomplete, now we get 2 users.
> 
> Solution: Cleanup state in the after Scenario.

Correct me if I am the wrong @kiranparajuli589 their is cleanup endpoint which cleanup the middleware at the end of tests run
[Screencast from 08-04-2022 11:36:37 AM.webm](https://user-images.githubusercontent.com/54478846/182773375-1063ef25-5464-4d3a-970b-43375432ed80.webm)

**Comment by kiranparajuli589** [comment]
True, @amrita-shrestha. AfterScenario does peform deleteion. Sorry, I completely overseen that. But seeing at your logs, not a single user is cleaned after the tests. If you run the same test, the test should pass because of `search -> delete -> create` follow on the create step.

I suggest looking at those delete requests in the AfterScenario. Do they run actually? If yes, we need to debug more about why these requests are failing.
